# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: π€ λ°°ν¬

on:
  pull_request:
    types: [ closed ]
    branches: [ "dev" ]
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DB_ENDPOINT: ${{ secrets.DEV_DB_ENDPOINT }}
      DB_NAME: ${{ secrets.DEV_DB_NAME }}
      DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: π”¨ JDK 17 μ„Έν…
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: π”¨ gradlew μ‹¤ν–‰ κ¶ν• μ„¤μ •
        run: chmod +x gradlew

      - name: π”¨ Gradle μΊμ‹ μ„¤μ •
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: π”¨ Gradle λΉλ“
        run: ./gradlew build --parallel

      - name: π“¦ λ°°ν¬ νμΌ μ¤€λΉ„
        run: |
          mkdir -p before-deploy
          cp ./build/libs/*.jar ./before-deploy/
          cp ./appspec.yml ./before-deploy/
          cp -r ./scripts/dev/ ./before-deploy/scripts/
          zip -r deploy.zip before-deploy/

      - name: π“¤ EC2μ— νμΌ μ—…λ΅λ“
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy.zip"
          target: "/home/ubuntu"

      - name: π€ EC2μ—μ„ λ°°ν¬ μ¤ν¬λ¦½νΈ μ‹¤ν–‰
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            unzip -o /home/ubuntu/deploy.zip -d /home/ubuntu
            rm -rf /home/ubuntu/app/*
            mv /home/ubuntu/before-deploy/* /home/ubuntu/app/
            chmod +x /home/ubuntu/app/scripts/*.sh
            /home/ubuntu/app/scripts/run_new_was.sh
            rm -rf /home/ubuntu/deploy.zip /home/ubuntu/before-deploy
